# traefik docker-compose.yml
# 
# Required Environment Variables:
#   HOST_DATA_PATH - Path on the host where Traefik data will be stored
#   HOSTNAME - The hostname for the host (e.g., server.local becomes...)
#             * proxy.server.local for accessing the Traefik dashboard
#             * whoami.server.local for accessing the Whoami test service 
#   FQDN - The fully qualified domain name for the host (e.g., server.example.com becomes...)
#             * proxy.server.example.com for accessing the Traefik dashboard
#             * whoami.server.example.com for accessing the Whoami test service 
#   CLOUDFLARE_DOMAIN - The main domain for the host (e.g., example.com)
#   CLOUDFLARE_DNS_API_TOKEN - Cloudflare API Token with DNS edit permissions for the DOMAIN

services:

  git-sync:
    image: k8s.gcr.io/git-sync/git-sync:v3.4.0 # A common git-sync image
    restart: always
    volumes:
      - ${HOST_CONFIG_PATH}:/git
    environment:
      GIT_SYNC_REPO: https://github.com/chilltemp/home-network.git
      GIT_SYNC_BRANCH: main
      GIT_SYNC_DEST: /git
      # Sync every 30 seconds
      GIT_SYNC_WAIT: 60
      # Use the volume path where git-sync writes files
      # Other specific options available for authentication, etc.
        
  traefik:
    image: traefik:v3.6
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

    networks:
     # Connect to the 'traefik_proxy' overlay network for inter-container communication across nodes
      - proxy

    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"

    environment:
      - CF_DNS_API_TOKEN=${CLOUDFLARE_DNS_API_TOKEN}
      
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${HOST_DATA_PATH}/certs:/certs:rw
      - ${HOST_DATA_PATH}/dynamic:/dynamic:ro
      - ${HOST_CONFIG_PATH}:/network-config:ro

    command:
      # EntryPoints
      - "--entrypoints.web.address=:80"
      # - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      # - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      # - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"

      # Attach the static configuration tls.yaml file that contains the tls configuration settings
      - "--providers.file.filename=/network-config/tls.yaml"

      # Providers 
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=proxy"

      # API & Dashboard 
      - "--api.dashboard=true"
      # - "--api.insecure=false"

      # Observability 
      - "--log.level=INFO"
      - "--accesslog=true"
      # - "--metrics.prometheus=true"

  # Traefik Dynamic configuration via Docker labels
    labels:
      # Enable self‑routing
      - "traefik.enable=true"

      # Dashboard router
      # - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.rule=Host(`proxy.${HOSTNAME}`)"
      # - "traefik.http.routers.dashboard.entrypoints=web"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard-home.rule=Host(`proxy.${FQDN}`)"
      # - "traefik.http.routers.dashboard-home.entrypoints=web"
      - "traefik.http.routers.dashboard-home.service=api@internal"

      - "traefik.http.routers.dashboard-secure.tls=true"
      - "traefik.http.routers.dashboard-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.dashboard-secure.tls.domains[0].main=${CLOUDFLARE_DOMAIN}"
      - "traefik.http.routers.dashboard-secure.tls.domains[0].sans=*.${CLOUDFLARE_DOMAIN}"

      # Basic‑auth middleware
      # - "traefik.http.middlewares.dashboard-auth.basicauth.users=<PASTE_HASH_HERE>"
      # - "traefik.http.routers.dashboard.middlewares=dashboard-auth@docker"

# Whoami application
  whoami:
    image: traefik/whoami
    container_name: whoami
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.${HOSTNAME}`)"
      - "traefik.http.routers.whoami-homelan.rule=Host(`whoami.${FQDN}`)"

networks:
  proxy:
    name: proxy

