# traefik docker-compose.yml
# 
# Required Environment Variables:
#   HOST_DATA_PATH - Path on the host where Traefik data will be stored
#   HOSTNAME - The hostname for the host (e.g., server.local becomes...)
#             * proxy.server.local for accessing the Traefik dashboard
#             * whoami.server.local for accessing the Whoami test service 
#   FQDN - The fully qualified domain name for the host (e.g., server.example.com becomes...)
#             * proxy.server.example.com for accessing the Traefik dashboard
#             * whoami.server.example.com for accessing the Whoami test service 
#   CLOUDFLARE_DOMAIN - The main domain for the host (e.g., example.com)
#   CLOUDFLARE_DNS_API_TOKEN - Cloudflare API Token with DNS edit permissions for the DOMAIN
# 
# Needs permissions to the DATA_*_PATH directories:
#   sudo chown -R 1000:1000 /data
#   mkdir -p /data/traefik/letsencrypt
#   echo {} > /data/traefik/letsencrypt/acme.json
#   sudo chown 1000:1000 /data/traefik/letsencrypt/acme.json

services:

  git-sync:
    image: k8s.gcr.io/git-sync/git-sync:v4.5.1
    restart: always
    user: "1000:1000"
    volumes:
      - ${HOST_CONFIG_PATH}:/git
    environment:
      GITSYNC_REPO: https://github.com/chilltemp/home-network.git
      GITSYNC_REF: main
      GITSYNC_LINK: /git/sync
      GITSYNC_ROOT: /git/root
      GITSYNC_PERIOD: 60s
      # https://github.com/kubernetes/git-sync?tab=readme-ov-file
        
  traefik:
    image: traefik:v3.6
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

    networks:
     # Connect to the 'traefik_proxy' overlay network for inter-container communication across nodes
      - proxy

    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"

    environment:
      - CF_DNS_API_TOKEN=${CLOUDFLARE_DNS_API_TOKEN}
      
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${HOST_DATA_PATH}/letsencrypt:/letsencrypt:rw
      - ${HOST_DATA_PATH}/dynamic:/dynamic:ro
      - ${HOST_CONFIG_PATH}:/network-config:ro

    command:
      # EntryPoints
      - "--entrypoints.web.address=:80"
      # - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      # - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      # - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"

      # Attach the static configuration tls.yaml file that contains the tls configuration settings
      # - "--providers.file.filename=/network-config/sync/traefik/tls.yml"

      # Providers 
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=proxy"

      # API & Dashboard 
      # - "--api.dashboard=true"
      - "--api.insecure=false"

      # Observability 
      - "--log.level=DEBUG"
      - "--accesslog=true"
      # - "--metrics.prometheus=true"

      - "--certificatesresolvers.cloudflare.acme.dnschallenge=true"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1:53,1.0.0.1:53"
      - "--certificatesresolvers.cloudflare.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.cloudflare.acme.email=${CLOUDFLARE_EMAIL}"
      - "--certificatesresolvers.cloudflare.acme.storage=/letsencrypt/acme.json"


  # Traefik Dynamic configuration via Docker labels
    labels:
      # Enable self‑routing
      - "traefik.enable=true"

      # Dashboard router
      - "traefik.http.routers.dashboard.rule=Host(`proxy.${HOSTNAME}`)"
      # - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.service=api@internal"

      - "traefik.http.routers.dashboard-home.rule=Host(`proxy.${FQDN}`)"
      # - "traefik.http.routers.dashboard-home.entrypoints=websecure"
      - "traefik.http.routers.dashboard-home.service=api@internal"

      - "traefik.http.routers.dashboard-home.tls=true"
      - "traefik.http.routers.dashboard-home.tls.certresolver=cloudflare.acme"
      - "traefik.http.routers.dashboard-home.tls.domains[0].main=${CLOUDFLARE_DOMAIN}"
      - "traefik.http.routers.dashboard-home.tls.domains[0].sans=*.${CLOUDFLARE_DOMAIN}"

      # Basic‑auth middleware
      # - "traefik.http.middlewares.dashboard-auth.basicauth.users=<PASTE_HASH_HERE>"
      # - "traefik.http.routers.dashboard.middlewares=dashboard-auth@docker"

# Whoami application
  whoami:
    image: traefik/whoami
    container_name: whoami
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.${HOSTNAME}`)"
      - "traefik.http.routers.whoami-homelan.rule=Host(`whoami.${FQDN}`)"

networks:
  proxy:
    name: proxy

